#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#yabai -m signal --add event=application_front_switched action="/Users/w0rng/projects/w0rng/scripts/swith_border.sh"


# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off\
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_opacity               off            \
    insert_feedback_color        0xff8A421D     \
    active_window_border_color   0xff8F421D     \
    normal_window_border_color   0xff555555     \
    window_border_width          2              \
    window_border_radius         0              \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    window_gap                   10             \
echo "yabai configuration loaded.."


# yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
# yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# padding_refresh_command="p=\$((\$(yabai -m query --windows --space | jq 'length') == 1 ? 0 : 10)) && \
#     yabai -m config --space mouse top_padding \$p && \
#     yabai -m config --space mouse bottom_padding \$p && \
#     yabai -m config --space mouse left_padding \$p && \
#     yabai -m config --space mouse right_padding \$p"
#
# yabai -m signal --add event=window_created action="$padding_refresh_command"
# yabai -m signal --add event=window_destroyed action="$padding_refresh_command"
# yabai -m signal --add event=application_launched action="$padding_refresh_command"
# yabai -m signal --add event=application_terminated action="$padding_refresh_command"
