- defaults:
    link:
      relink: true

- create:
    - ~/.config

- link:
    ~/.config/yabai: configs/yabai
    ~/.config/alacritty: configs/alacritty
    ~/.config/karabiner: configs/karabiner
    ~/.config/doom: configs/doom
    ~/.config/nvim: configs/nvim
    ~/.config/skhd: configs/skhd
    ~/.config/lazydocker: configs/lazydocker
    ~/.config/lazygit: configs/lazygit
    ~/.gitconfig: configs/git/gitconfig
    # python
    ~/.isort.cfg: configs/python/isort.cfg
    ~/.config/flake8: configs/python/flake8

- tap:
    - d12frosted/emacs-plus
    - koekeishiya/formulae

- brew:
    - bandit
    - bat
    - fish
    - fzf
    - neovim
    - pyenv
    - starship
    - thefuck
    - uv
    - d12frosted/emacs-plus/emacs-plus@29 --with-native-comp
    - koekeishiya/formulae/skhd
    - koekeishiya/formulae/yabai

- cask:
    - alacritty
    - chromium
    - font-fira-code
    - obsidian
    - raycast
    - vscodium
    - insomnium
    - pycharm
    - jetbrains-toolbox

- firefox:
    user.js: firefox/user.js

- shell:
    - [ git submodule update --init --recursive, Installing submodules ]
