- defaults:
    link:
      relink: true

- create:
    - ~/.config

- link:
    ~/.config/fish: configs/fish
    ~/.config/alacritty: configs/alacritty
    ~/.config/karabiner: configs/karabiner
    ~/.config/lazydocker: configs/lazydocker
    ~/.config/lazygit: configs/lazygit
    ~/.gitconfig: configs/git/gitconfig
    ~/.config/zed: configs/zed
    # python
    ~/.isort.cfg: configs/python/isort.cfg
    ~/.config/flake8: configs/python/flake8

- brew:
    - bandit
    - bat
    - fish
    - fzf
    - pyenv
    - starship
    - thefuck
    - uv
    - mas-cli/tap/mas

- cask:
    - alacritty
    - font-fira-code
    - obsidian
    - raycast
    - orbstack
    - telegram
    - shottr
    - appcleaner
    - keka

- app-store:
    # safari extensions
    - 6720708363 # obsidian web clipper
    - 1544743900 # hush
    - 1458969831 # JSONPeep
    - 6451469297 # DeArrow
    - 1320666476 # Wipr
    - 1573461917 # SponsorBlock
    # apps
    - 1554411065 # pomodoro
    - 1452453066 # Hidden Bar

- shell:
    - [git submodule update --init --recursive, Installing submodules]
