import = ["/Users/w0rng/.config/alacritty/themes/solarized_dark.toml"]
live_config_reload = true

[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 10

[window]
#decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 10
y = 0

[cursor]
style = "Beam"
thickness = 0.2
